modulised static files in different directory (static), and images in…
CsqLang/CsqLang.github.io pull request #3
Opened 2023-09-10 15:19 UTC by usmanmusa1920

I modulised static files in different directory called (static), and images in (media), also added .gitignore, and LICENSE file

2023-09-10 20:10 UTC, gekkowrld requested changes
Thanks for your contribution. Can you structure the files 'logically'. You can follow this guide <https://binaryrambo.com/html-project-structure/> on how to arrange the files. Only index.html should in the root folder (the only .html file at least).

2023-09-10 20:10 UTC, gekkowrld commented on static/index.js
This file (or atleast the code) is currently useless. It doesn't work. You can remove it.

2023-09-10 20:10 UTC, gekkowrld commented on .gitignore
Unless anything is to be ignored, you should remove this file in its entirety.

2023-09-10 20:10 UTC, gekkowrld commented on static/style.css
[Suggestion]
Try to use as few .css files as possible. This will reduce code duplication.

2023-09-11 04:15 UTC, usmanmusa1920 commented on static/index.js
yes you are right, but I include it, because i just want to structure the files, not adding or beautifying anything. Thank you!

2023-09-11 04:17 UTC, usmanmusa1920 commented on .gitignore
It is good idea to include `.githiubignore` file because sometimes you don't know and these .ignore file the create themselves.

2023-09-11 04:18 UTC, usmanmusa1920 commented on static/style.css
indeed and that is good idea!

2023-09-11 11:09 UTC, gekkowrld commented on .gitignore
In this case it is not required. You can safely remove it. And the files being ignored are for python which is not used anywhere.

2023-09-12 01:57 UTC, usmanmusa1920 commented
everything now is right!

2023-09-15 18:35 UTC, gekkowrld commented
Thanks @usmanmusa1920 for your contribution, hope you continue to contribute.

2023-09-15 18:35 UTC, gekkowrld approved these changes

2023-09-15 18:37 UTC, merged

2023-09-16 12:05 UTC, usmanmusa1920 commented
indeed @gekkowrld thanks!